### ISSUE TITLE
New title key fetching results in bad ticket generation

### ISSUE THREAD

**Issue by ghost** [thegamershollow/NUSPY#4]
New tickets being generated are anywhere from `830` - `840` bytes with bad info in them. Correct generation is `848` bytes.

I assume this is because of bad fetching when it comes to the library as I've put in some debug statements to print the information it's fetching. Oftentimes no title key is returned, or it just straight up gives the wrong information.

I'll work on a fix for it.

**Comment by ghost** [comment]
The problem is probably case-sensitivity. I recommend updating your Library to be all upper-cased for both Title IDs / Keys and converting any user input to upper case as well.

So if a user inputs the Title ID `0005000c101d9d00` instead of searching for that specific case, it will be converted to `0005000C101D9D00` and search for `0005000C101D9D00` in the library. Because currently if someone say inputs `0005000C101D9D00` it searches for `0005000c101d9d00` which returns nothing because of case-sensitivity.

**Comment by ghost** [comment]
Figured out a fix that might not need you to change anything, but I'll make a fork and pull request regardless.

**Comment by ghost** [comment]
Added fixes to both Script and Lib in their respective Pull Requests.

**Comment by thegamershollow** [comment]
thank you for the help
